# ESP32-S3-Touch-LCD-7
substitutions:
  name: "lcd01"
  friendly_name: "Kitchen"
  room: "Kitchen"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/DJL-F3D/esphome-lvgl/
    file: guition-esp32-s3-4848s040/package.yaml
    refresh: 1sec
